# Generated by Django 5.0 on 2023-12-25 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_verifycode_email_alter_verifycode_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifyCode',
        ),
        migrations.AlterField(
            model_name='emailverifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
